### ISSUE TITLE
Atomからgit commitできない

### ISSUE THREAD

**Issue by takaze** [takaze/test#2]
AtomのタブからCommitすると

「user.name, user.mailが設定されてないよ！」

と怒られてしまう。
なおPull、Pushは可能（おそらくAtomにアクセストークンを設定したため）

Atom内蔵？のgitの設定はどこにあるのだろう…

**Comment by hitobb** [comment]
自主的に使いこなしていらっしゃるw
さすがですね！

Atomは標準だとgitをコントロールするライブラリが足りていなかったような、、、
これ組み込んでテストしてみてください。

http://shinya131-note.hatenablog.jp/entry/2015/05/31/154831

取り急ぎ。

**Comment by takaze** [comment]
調べてみると今年になってgit内蔵したみたいですが

> integrate が incomplete だから、コンソールからgit叩けよ！hahaha！

とのことなので、大人しくCUI使いますｗ
Atom自体はMarkup言語で使ってる人が多いみたいですね。
触った感じは好きだからしばらく使ってみます。

**Comment by hitobb** [comment]
なるほど、そんな制約が。

ちなみに、機能は全然これっぽっちも足りていませんが、
初心者用のGUIツールとして、こういうものもあります。

https://desktop.github.com/

pull→commit→pushの流れを理解するためには使えるかもですので、
CLIに疲れたら、こちらも触ってみてください。
ちょっとした画像ファイルなんかをUPするときは、こっちのほうが楽ですｗ

ご参考になれば。

**Comment by hitobb** [comment]
ミッションです！
この会話、１６日前に完結しているっぽいので、クローズしてみてくださいな。

**Comment by takaze** [comment]
おお、openのままだった…cleseします！
